### ISSUE TITLE
Help building lineageos

### ISSUE THREAD

**Issue by skjnldsv** [xiaomi-sdm660/android_device_xiaomi_jasmine_sprout#1]
Hello, could you share your manifest file for automated lineageos builds? I'd like to build my own versions of lineageos-microg :)

Thanks a lot for your help!
Cheers

**Comment by rcstar6696** [comment]
All is public in manifest repo just not updated

**Comment by skjnldsv** [comment]
Thanks!! Do you know if trying this for lineageos 15.1 would work?
Are vendor and other repo compatible?

**Comment by rcstar6696** [comment]
No it will not work on oreo we only support pie

**Comment by skjnldsv** [comment]
How unfortunate. :/
Thanks anyway! :)
