### ISSUE TITLE
Getting error when compiling los-16.0-new with lineage source tree

### ISSUE THREAD

**Issue by umerfaruque** [xiaomi-sdm660/android_device_xiaomi_jasmine_sprout#5]
Getting following error when compiling los-16.0-new with lineage 16.0 source code 

Error: The following instances are in the device manifest but not specified in framework compatibility matrix: 
    vendor.lineage.livedisplay@2.0::IDisplayModes/default
    vendor.lineage.livedisplay@2.0::IPictureAdjustment/default
    vendor.xiaomi.hardware.mlipay@1.0::IMlipayService/default

Please guide me which branch is suitable and stable for jasmine_sprout global version

**Comment by ghost** [comment]
None of the branches is suitable, add those in vendor_framework_compatibility_matrix.xml of commit tree, it's an issue of common tree and not device tree.

**Comment by AkshayKakatkar** [comment]
Add these in that file
    <hal format="hidl" optional="true">
         <name>vendor.lineage.livedisplay</name>
         <version>2.0</version>
         <interface>
             <name>IDisplayModes</name>
             <instance>default</instance>
         </interface>
         <interface>
            <name>IPictureAdjustment</name>
            <instance>default</instance>
         </interface>
     </hal>
    <hal format="hidl" optional="true">
         <name>vendor.qti.data.factory</name>
         <version>1.1</version>
         <interface>
             <name>IFactory</name>
             <instance>default</instance>
         </interface>
     </hal>
